inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 250

Metrics/BlockLength:
  Enabled: false
